version: '3.3'
networks: 
    rabbit:
        driver: bridge

services:
    
    rabbitmq:
        image: "rabbitmq:3"
        container_name: RABBIT_MQ
        ports: 
            - 5672:5672
        networks: 
            - rabbit